// <auto-generated />
namespace TemaXP.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class fixed_image_src : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(fixed_image_src));
        
        string IMigrationMetadata.Id
        {
            get { return "201509091055213_fixed_image_src"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
